version: "3.8"

services:
  # ------------------------------------
  # 1. СЕРВИС БЭКЕНДА (Spring Boot)
  # ------------------------------------
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: jobapp-backend
    depends_on:
      - db
    env_file:
      - ./backend.env
    dns:
      - 8.8.8.8
      - 1.1.1.1

  # ------------------------------------
  # 2. СЕРВИС ФРОНТЕНДА (React + Nginx)
  # ------------------------------------
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: jobapp-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: always

volumes:
  db-data: {}
